# Jim; I'm giving up on this docker thing. It just fails ,and I've spent about six weeks on this...
name: Publish Docker Image
on:
  # change to only trigger on push: branches: [ main ]
  push:
  pull_request:
    branches: [ main ]
jobs:
  push_to_registry:
    name: Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      # For pushing to Dockerhub, uncomment line 18-30

      #- name: Login to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #    password: ${{ secrets.DOCKER_HUB_TOKEN }}

      #- name: Build and Push to Dockerhub
      #  uses: docker/build-push-action@v3
      #  with:
      #    context: .
      #    file: ./Dockerfile
      #    push: true
      #    tags: ${{ secrets.DOCKER_HUB_USERNAME }}/shopifly:latest

      - name: Build and Push to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t shopifly
          docker tag shotifly 244530008913.dkr.ecr.eu-west-1.amazonaws.com/1025:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/1025:$rev